/**
 * build-tw5-vendor.ts — vendor TW5 external core JS for isomorphic browser boot.
 *
 * Generates two artifacts:
 *
 *   1. packages/lararium-app/public/tiddlywikicore-<version>.js
 *      TW5's own prebuilt browser bundle via $:/core/templates/tiddlywiki5.js.
 *      Contains all $tw.modules.define() calls — browser-native, no vm/fs needed.
 *      Served as a static asset; loaded via <script> before LarariumTW5.boot().
 *      suppressBoot is set by the HTML before the script loads so $tw is populated
 *      but boot() is not called — LarariumTW5 calls it after injecting preloads.
 *
 *   2. packages/lararium-tw5/src/generated-tw5-version.ts
 *      Exports TW5_VERSION and TW5_CORE_SCRIPT_PATH so boot code can reference
 *      the pinned script filename without hardcoding it.
 *
 * Usage:
 *   pnpm --filter @lararium/tw5 run build:tw5-vendor
 *
 * Pinned version: update TW5_VERSION below and re-run to upgrade.
 */

import { writeFileSync, mkdirSync } from "fs";
import { join, resolve, relative, dirname } from "path";
import { fileURLToPath } from "url";
import { createRequire } from "module";

const __dirname = fileURLToPath(new URL(".", import.meta.url));
const _require = createRequire(import.meta.url);

const TW5_VERSION = "5.4.0";
const TW5_SCRIPT_FILENAME = `tiddlywikicore-${TW5_VERSION}.js`;

// Resolve paths relative to monorepo root
const MONOREPO_ROOT  = resolve(__dirname, "../../..");
const APP_PUBLIC_DIR = join(MONOREPO_ROOT, "packages/lararium-app/public");
const CORE_JS_OUT    = join(APP_PUBLIC_DIR, TW5_SCRIPT_FILENAME);
const VERSION_TS_OUT = resolve(__dirname, "../src/generated-tw5-version.ts");

// ---------------------------------------------------------------------------
// Step 1 — Generate tiddlywikicore-<version>.js using TW5's render pipeline
// ---------------------------------------------------------------------------

console.log(`build-tw5-vendor: generating ${TW5_SCRIPT_FILENAME} via TW5 render pipeline…`);

const tw = _require("tiddlywiki");
const path = _require("path");
const fs = _require("fs");

const tmpOut = join(MONOREPO_ROOT, ".tw5-vendor-tmp");
mkdirSync(tmpOut, { recursive: true });

await new Promise<void>((resolve_p, reject) => {
  const instance = tw.TiddlyWiki();
  const editionsEmpty = path.resolve(
    dirname(_require.resolve("tiddlywiki")),
    "../../editions/empty",
  );
  instance.boot.argv = [
    editionsEmpty,
    "--rendertiddler", "$:/core/templates/tiddlywiki5.js",
    join(tmpOut, TW5_SCRIPT_FILENAME),
    "text/plain",
  ];
  instance.boot.boot(() => {
    const generated = join(tmpOut, TW5_SCRIPT_FILENAME);
    if (!fs.existsSync(generated)) {
      reject(new Error(`TW5 render did not produce ${generated}`));
      return;
    }
    mkdirSync(APP_PUBLIC_DIR, { recursive: true });
    fs.copyFileSync(generated, CORE_JS_OUT);
    // cleanup tmp
    fs.rmSync(tmpOut, { recursive: true, force: true });
    resolve_p();
  });
});

const sizeKb = Math.round(fs.statSync(CORE_JS_OUT).size / 1024);
console.log(`build-tw5-vendor: wrote ${CORE_JS_OUT} (${sizeKb} kB)`);

// ---------------------------------------------------------------------------
// Step 2 — Generate generated-tw5-version.ts
// ---------------------------------------------------------------------------

const versionTs = `\
// AUTO-GENERATED by scripts/build-tw5-vendor.ts — do not edit.
// Update TW5_VERSION in build-tw5-vendor.ts and re-run build:tw5-vendor to upgrade.

export const TW5_VERSION = "${TW5_VERSION}";

/** Filename of the vendored external core script served at /public. */
export const TW5_CORE_SCRIPT_FILENAME = "${TW5_SCRIPT_FILENAME}";

/** URL path at which serve.ts exposes the external core. */
export const TW5_CORE_SCRIPT_URL = "/${TW5_SCRIPT_FILENAME}";
`;

writeFileSync(VERSION_TS_OUT, versionTs, "utf-8");
console.log(`build-tw5-vendor: wrote ${relative(process.cwd(), VERSION_TS_OUT)}`);

// ---------------------------------------------------------------------------
// Done — note: generated-tw5-core-modules.ts is no longer needed and can be
// deleted once serve.ts + LarariumTW5 are wired to the external core script.
// ---------------------------------------------------------------------------

console.log(`build-tw5-vendor: done. Pin: tiddlywiki@${TW5_VERSION} → ${TW5_SCRIPT_FILENAME}`);
