/**
 * build-tw5-vendor.ts — generate generated-tw5-core-modules.ts
 *
 * Reads all 354 TW5 core module .js files from the tiddlywiki npm package.
 * Each file has a /*\ header block declaring title, type, module-type.
 * Emits them as a preloadTiddlers array so LarariumTW5.boot() can supply
 * them in browser environments where fs is not available.
 *
 * In Node.js, TW5 loads these from $tw.boot.bootPath via fs.readFileSync.
 * In browser, fs is stubbed → modules never load → wiki methods missing.
 * Preloading the modules as tiddlers fixes both environments identically.
 *
 * Usage:
 *   pnpm --filter @lararium/tw5 run build:tw5-vendor
 *
 * Output:
 *   packages/lararium-tw5/src/generated-tw5-core-modules.ts
 */

import { readFileSync, writeFileSync, readdirSync, statSync } from "fs";
import { join, resolve, relative } from "path";
import { fileURLToPath } from "url";

const __dirname = fileURLToPath(new URL(".", import.meta.url));
const TW5_VERSION = "5.4.0";
const TW5_ROOT = resolve(__dirname, `../../../node_modules/.pnpm/tiddlywiki@${TW5_VERSION}/node_modules/tiddlywiki`);
const MODULES_PATH = join(TW5_ROOT, "core/modules");
const OUT_PATH = resolve(__dirname, "../src/generated-tw5-core-modules.ts");

// ---------------------------------------------------------------------------
// Parse the /*\ header block from a TW5 module file
// ---------------------------------------------------------------------------

interface ModuleMeta {
  title: string;
  type: string;
  moduleType: string;
}

function parseHeader(source: string): ModuleMeta | null {
  // Header format:
  //   /*\
  //   title: $:/core/modules/wiki.js
  //   type: application/javascript
  //   module-type: wikimethod
  //   \*/
  const match = source.match(/^\/\*\\([\s\S]*?)\\?\*\//m);
  if (!match) return null;
  const block = match[1];
  const get = (key: string) => {
    const m = block.match(new RegExp(`^${key}:\\s*(.+)$`, "m"));
    return m ? m[1].trim() : null;
  };
  const title = get("title");
  const type = get("type") ?? "application/javascript";
  const moduleType = get("module-type");
  if (!title || !moduleType) return null;
  return { title, type, moduleType };
}

// ---------------------------------------------------------------------------
// Walk the modules directory recursively
// ---------------------------------------------------------------------------

function walkDir(dir: string, results: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      walkDir(full, results);
    } else if (entry.endsWith(".js")) {
      results.push(full);
    }
  }
  return results;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

const files = walkDir(MODULES_PATH);
console.log(`build-tw5-vendor: found ${files.length} JS files in ${relative(process.cwd(), MODULES_PATH)}`);

interface TiddlerEntry {
  title: string;
  type: string;
  "module-type": string;
  text: string;
}

const tiddlers: TiddlerEntry[] = [];
let skipped = 0;

for (const file of files) {
  const source = readFileSync(file, "utf-8");
  const meta = parseHeader(source);
  if (!meta) {
    skipped++;
    continue;
  }
  tiddlers.push({
    title: meta.title,
    type: meta.type,
    "module-type": meta.moduleType,
    text: source,
  });
}

console.log(`build-tw5-vendor: parsed ${tiddlers.length} module tiddlers (${skipped} skipped — no header)`);

// Emit TypeScript
const ts = `\
// AUTO-GENERATED by scripts/build-tw5-vendor.ts — do not edit.
// TiddlyWiki ${TW5_VERSION} core module tiddlers for isomorphic browser boot.
// Preloaded by LarariumTW5.boot() so TW5 core modules resolve without fs.

export const TW5_CORE_MODULE_TIDDLERS: ReadonlyArray<Record<string, string>> = ${JSON.stringify(tiddlers, null, 2)} as const;
`;

writeFileSync(OUT_PATH, ts, "utf-8");
console.log(`build-tw5-vendor: wrote ${tiddlers.length} tiddlers to ${relative(process.cwd(), OUT_PATH)}`);
