/**
 * write-ui-preloads.ts — generates src/generated-ui-preloads.ts from lares/ui memes.
 *
 * Reads all lares/ha-ka-ba/api/v0.1/lararium/ui/*.md files, extracts:
 *   - The #iam TOML block → tiddler fields (title, tags, list-after, etc.)
 *   - The body between STX/ETX → tiddler text
 *
 * Emits UI_PRELOAD_TIDDLERS: an array of tiddler field objects that
 * lararium-tw5.ts pushes into instance.preloadTiddlers at boot.
 *
 * Only memes with content-type "text/vnd.tiddlywiki" are included —
 * JS module memes are handled by the bundle path.
 *
 * Run via: tsx scripts/write-ui-preloads.ts
 */

import { readFileSync, writeFileSync, readdirSync } from "fs";
import { resolve, dirname, basename } from "path";
import { fileURLToPath } from "url";

const __dirname  = dirname(fileURLToPath(import.meta.url));
const root       = resolve(__dirname, "../../..");
const uiDir      = resolve(root, "lares/ha-ka-ba/api/v0.1/lararium/ui");
const outPath    = resolve(__dirname, "../src/generated-ui-preloads.ts");

const STX_RE = /<<~[^>]*&#x0002;[^>]*>>/;
const ETX_RE = /<<~[^>]*&#x0003;[^>]*>>/;
const TOML_RE = /```toml([\s\S]*?)```/;
const SOH_URI_RE = /<<~[^>]*&#x0001;[^>]*\?\s*->\s*([^\s>]+)\s*>>/;

function parseToml(block: string): Record<string, string | string[]> {
  const out: Record<string, string | string[]> = {};
  for (const line of block.split("\n")) {
    const m = line.match(/^([\w-]+)\s*=\s*(.+)$/);
    if (!m) continue;
    const [, key, rawVal] = m;
    const val = rawVal!.trim();
    if (val.startsWith("[")) {
      // Array value — extract quoted strings
      out[key!] = [...val.matchAll(/"([^"]*)"/g)].map((x) => x[1]!);
    } else {
      out[key!] = val.replace(/^"|"$/g, "");
    }
  }
  return out;
}

type TiddlerFields = Record<string, string | string[]>;

const tiddlers: TiddlerFields[] = [];

for (const file of readdirSync(uiDir).filter((f) => f.endsWith(".md"))) {
  const text = readFileSync(resolve(uiDir, file), "utf8");

  // Extract URI from SOH
  const uriMatch = SOH_URI_RE.exec(text);
  if (!uriMatch) { console.warn(`write-ui-preloads: no SOH URI in ${file}`); continue; }
  const uri = uriMatch[1]!;

  // Extract #iam TOML
  const tomlMatch = TOML_RE.exec(text);
  if (!tomlMatch) { console.warn(`write-ui-preloads: no TOML block in ${file}`); continue; }
  const fields = parseToml(tomlMatch[1]!);

  // Only wikitext content types go through this path
  if (fields["content-type"] !== "text/vnd.tiddlywiki") continue;

  // Extract body between STX/ETX
  const stxMatch = STX_RE.exec(text);
  const etxMatch = ETX_RE.exec(text);
  if (!stxMatch || !etxMatch) { console.warn(`write-ui-preloads: no STX/ETX in ${file}`); continue; }
  const stxEnd   = stxMatch.index + stxMatch[0].length;
  const etxStart = etxMatch.index;
  // Skip the #hud-fields and other ahu slots — only take the immediate body after STX
  // (before the first <<~ ahu that isn't a close)
  let body = text.slice(stxEnd, etxStart).trim();
  // Strip any trailing ahu slots (edges etc) — body is everything up to first <<~ ahu
  const ahuOpen = body.indexOf("<<~ ahu ");
  if (ahuOpen > 0) body = body.slice(0, ahuOpen).trim();

  tiddlers.push({
    title: `lar:///${uri.replace(/^lar:\/\/\//, "")}`,
    text:  body,
    type:  "text/vnd.tiddlywiki",
    tags:  fields["tags"] ?? [],
    ...(fields["list-after"] ? { "list-after": fields["list-after"] as string } : {}),
    ...(fields["list-before"] ? { "list-before": fields["list-before"] as string } : {}),
  });

  console.log(`write-ui-preloads: processed ${basename(file)} → ${uri}`);
}

const lines = [
  "// AUTO-GENERATED by scripts/write-ui-preloads.ts — do not edit by hand.",
  "// Re-run: pnpm --filter @lararium/tw5 build:ui",
  "",
  "export const UI_PRELOAD_TIDDLERS: Array<Record<string, string | string[]>> = ",
  JSON.stringify(tiddlers, null, 2) + ";",
  "",
];

writeFileSync(outPath, lines.join("\n"), "utf8");
console.log(`write-ui-preloads: wrote ${tiddlers.length} tiddlers to ${outPath}`);
