/**
 * write-vendor-plugins.ts — generates src/generated-vendor-plugins.ts from
 * lares/ha-ka-ba/api/v0.1/vendor/tw5-plugins/*.json
 *
 * Each JSON file must be a TW5 plugin bundle tiddler (single object with a
 * `type: application/json` field and a `text` field containing the sub-tiddlers).
 *
 * Run via: pnpm --filter @lararium/tw5 build:vendors
 */

import { readFileSync, writeFileSync, readdirSync } from "fs";
import { resolve, dirname, basename } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root      = resolve(__dirname, "../../..");
const vendorDir = resolve(root, "lares/ha-ka-ba/api/v0.1/tw5-plugins");
const outPath   = resolve(__dirname, "../src/generated-vendor-plugins.ts");

type PluginFields = Record<string, string | undefined>;

const plugins: PluginFields[] = [];

for (const file of readdirSync(vendorDir).filter((f) => f.endsWith(".json"))) {
  const raw     = readFileSync(resolve(vendorDir, file), "utf8");
  const bundle  = JSON.parse(raw) as PluginFields;
  if (!bundle["title"]) { console.warn(`write-vendor-plugins: no title in ${file}`); continue; }
  plugins.push(bundle);
  console.log(`write-vendor-plugins: loaded ${basename(file)} → ${bundle["title"]} v${bundle["version"] ?? "?"}`);
}

const lines = [
  "// AUTO-GENERATED by scripts/write-vendor-plugins.ts — do not edit by hand.",
  "// Re-run: pnpm --filter @lararium/tw5 build:vendors",
  "",
  "export const VENDOR_PLUGIN_TIDDLERS: Array<Record<string, string>> = ",
  JSON.stringify(plugins, null, 2) + ";",
  "",
];

writeFileSync(outPath, lines.join("\n"), "utf8");
console.log(`write-vendor-plugins: wrote ${plugins.length} plugin(s) to ${outPath}`);
