title: Synthetic Dream Machine
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
# Global publishing settings
future: true
permalink: /:title/
include: [".htaccess"]
# Front Matter Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
