title: Synthetic Dream Machine
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
plugins:
  - jekyll-optional-front-matter
source: .
exclude:
  - .bundle
  - .bundle/**
  - .venv
  - .venv/**
  - vendor
  - vendor/**
  - AGENTS.md
  - Lares_A_CustomGPT_System_Prompt.md
  - Campaigns
# Global publishing settings
future: true
permalink: /:title/
include: [".htaccess"]
# Front Matter Defaults
# optional defaults so you don't need layout in every file
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
