.PHONY: help install build test typecheck serve dev reseed clean \
        docker-build docker-serve docker-dev docker-qa docker-prod docker-smoke

help:
	@echo "Development:"
	@echo "  make install       Install all workspace dependencies"
	@echo "  make build         Build all packages (core → tw5 → tldraw → node → app → mcp)"
	@echo "  make test          Run all package test suites"
	@echo "  make typecheck     Run tsc --noEmit across all packages"
	@echo "  make serve         Build then run node relay peer on :4321 (catalog URL printed to console)"
	@echo "  make dev           Run node peer (:8080) + Vite dev server (:5173) concurrently"
	@echo "  make reseed        Force-reseed corpus:lares island (server must be running)"
	@echo "  make clean         Remove all dist/ and .lararium-data/ artifacts"
	@echo ""
	@echo "Auth (optional — GitHub OAuth web flow):"
	@echo "  GITHUB_CLIENT_ID=<id> GITHUB_CLIENT_SECRET=<secret> make serve"
	@echo "  gh CLI session is used automatically when available (developer path)."
	@echo "  Bluesky AT Proto OAuth is always available in the browser (no config needed)."
	@echo ""
	@echo "Docker:"
	@echo "  make docker-build  Build serve + mcp Docker images"
	@echo "  make docker-dev    docker compose --profile dev (tsx watch)"
	@echo "  make docker-qa     docker compose --profile qa (built, ports exposed)"
	@echo "  make docker-prod   docker compose --profile prod (hardened, no ports)"
	@echo "  make docker-smoke  docker compose --profile qa-smoke (stdio smoke tests)"

# ---------------------------------------------------------------------------
# Local dev
# ---------------------------------------------------------------------------

install:
	pnpm install

build:
	pnpm -r build

test:
	pnpm -r test

typecheck:
	pnpm -r typecheck

serve: build
	LAR_PORT=4321 node packages/lararium-node/dist/src/main.js

# Hot-reload for active development: node peer (:8080) + Vite HMR (:5173) concurrently.
# Vite proxies /ws and /api to :8080 — no static serving needed from node in dev.
dev:
	pnpm --filter @lararium/node exec tsx src/main.ts & pnpm --filter @lararium/app exec vite

reseed:
	@echo "[reseed] open the relay console — catalog URL is printed on boot."
	@echo "[reseed] navigate to http://localhost:4321/#<catalog-url> to join."

clean:
	find . -path "*/node_modules" -prune -o -name "dist" -type d -print | grep -v node_modules | xargs rm -rf
	rm -rf .lararium-data
	# dist-bundle (lararium-tw5 vite bundle output — missed by dist/ sweep)
	rm -rf packages/lararium-tw5/dist-bundle
	# gitignored generated source files
	rm -rf packages/lararium-core/src/generated
	rm -f packages/lararium-tw5/src/generated-tw5-version.ts
	rm -f packages/lararium-tw5/src/generated-ui-preloads.ts
	# vendored TW5 browser bundle (regenerated by build:tw5-vendor)
	rm -f packages/lararium-app/public/tiddlywikicore-*.js
	# ghost dirs from old sync-heleuma repoRoot bug
	rm -rf packages/lararium-core/packages
	# python build artifacts
	rm -rf lares.egg-info
	# temp dir from build-tw5-vendor
	rm -rf .tw5-vendor-tmp

# ---------------------------------------------------------------------------
# Docker
# ---------------------------------------------------------------------------

docker-build:
	docker compose build

docker-dev:
	docker compose --profile dev up

docker-qa:
	docker compose --profile qa up

docker-prod:
	docker compose --profile prod up

docker-smoke:
	docker compose --profile qa-smoke run --rm lararium-qa-smoke
