/**
 * Browser-side TW5 filter engine — same operators, same grammar as the Node path.
 *
 * Uses the pre-built browser bundle generated by scripts/build-tw-browser-filter.mjs.
 * Regenerate the bundle when tiddlywiki devDependency is bumped:
 *   node scripts/build-tw-browser-filter.mjs
 *
 * This module is aliased in vite.config.ts:
 *   "@lararium/core/tw-filter" → "@lararium/core/tw-filter-browser"
 * so that browser bundles transparently get this implementation instead of the
 * Node-only tw-filter.ts (which uses createRequire).
 *
 * API is identical to tw-filter.ts so callers don't need env conditionals.
 */

import { createBrowserFilterWiki, type BrowserFilterWiki } from "./generated/tw-filter-engine.browser.js";
import type { ClosureEntry } from "./compiler.js";

// ---------------------------------------------------------------------------
// Singleton wiki (browser — one instance, lazy, sync)
// ---------------------------------------------------------------------------

let _wiki: BrowserFilterWiki | null = null;
let _loadedUris = new Set<string>();

function getWiki(allEntries: readonly ClosureEntry[]): BrowserFilterWiki {
  if (!_wiki) {
    _wiki = createBrowserFilterWiki(allEntries.map(entryToTiddler));
    for (const e of allEntries) _loadedUris.add(e.uri);
  }
  return _wiki;
}

function entryToTiddler(entry: ClosureEntry): { fields: Record<string, string | string[]> } {
  return {
    fields: {
      title:        entry.uri,
      tags:         entry.implements,
      depth:        String(entry.depth),
      rating:       entry.kind,
      role:         entry.role ?? "",
      exists:       String(entry.exists),
      laresRelPath: entry.laresRelPath ?? "",
      contentHash:  entry.contentHash,
    },
  };
}

function toCanonicalTW(expr: string): string {
  return expr.replace(/\ball\[memes\]/g, "all[tiddlers]");
}

// ---------------------------------------------------------------------------
// Public API (mirrors tw-filter.ts)
// ---------------------------------------------------------------------------

/**
 * Filter ClosureEntry objects using TW5's filter engine (browser-side).
 * Synchronous — no async boot needed in browser (bundle is pre-initialized).
 *
 * Accepts TW5 filter expressions identically to the Node filterMemesTW().
 * [all[memes]] alias works the same way.
 */
export function filterMemesBrowser(
  allEntries: readonly ClosureEntry[],
  expr: string,
): ClosureEntry[] {
  const wiki = getWiki(allEntries);
  const titles = wiki.filterTiddlers(toCanonicalTW(expr));
  const byUri = new Map(allEntries.map((e) => [e.uri, e]));
  return titles.map((t) => byUri.get(t)).filter((e): e is ClosureEntry => e !== undefined);
}

/**
 * Async wrapper matching the Node filterMemesTW() signature.
 * Enables isomorphic code that uses the same call signature in both environments.
 */
export async function filterMemesTW(
  allEntries: readonly ClosureEntry[],
  expr: string,
): Promise<ClosureEntry[]> {
  return filterMemesBrowser(allEntries, expr);
}

/**
 * Pre-compute multiple named filter results (browser sync version).
 */
export async function precomputeRooms(
  allEntries: readonly ClosureEntry[],
  rooms: Record<string, string>,
): Promise<Record<string, string[]>> {
  const wiki = getWiki(allEntries);
  const result: Record<string, string[]> = {};
  const byUri = new Map(allEntries.map((e) => [e.uri, e]));
  for (const [roomId, expr] of Object.entries(rooms)) {
    const titles = wiki.filterTiddlers(toCanonicalTW(expr));
    result[roomId] = titles.filter((t) => byUri.has(t));
  }
  return result;
}
