/**
 * Browser-side TW5 filter engine — same operators, same grammar as the Node path.
 *
 * Uses the pre-built browser bundle generated by scripts/build-tw-browser-filter.mjs.
 * Regenerate the bundle when tiddlywiki devDependency is bumped:
 *   node scripts/build-tw-browser-filter.mjs
 *
 * This module is aliased in vite.config.ts:
 *   "@lararium/core/tw-filter" → "@lararium/core/tw-filter-browser"
 * so that browser bundles transparently get this implementation instead of the
 * Node-only tw-filter.ts (which uses createRequire).
 *
 * API is identical to tw-filter.ts so callers don't need env conditionals.
 */

import { createBrowserFilterWiki, type BrowserFilterWiki } from "./generated/tw-filter-engine.browser.js";
import type { ClosureEntry } from "./compiler.js";

// ---------------------------------------------------------------------------
// Singleton wiki (browser — one instance, lazy, sync)
// ---------------------------------------------------------------------------

let _wiki: BrowserFilterWiki | null = null;
let _loadedUris = new Set<string>();

function getWiki(allEntries: readonly ClosureEntry[]): BrowserFilterWiki {
  if (!_wiki) {
    _wiki = createBrowserFilterWiki(allEntries.map(entryToTiddler));
    for (const e of allEntries) _loadedUris.add(e.uri);
  }
  return _wiki;
}

function entryToTiddler(entry: ClosureEntry): { fields: Record<string, string | string[]> } {
  return {
    fields: {
      title:        entry.uri,
      tags:         entry.implements,
      depth:        String(entry.depth),
      rating:       entry.kind,
      confidence:   String(entry.confidence),
      register:     entry.register,
      manaoio:      String(entry.manaoio),
      mana:         String(entry.mana),
      manao:        String(entry.manao),
      role:         entry.role ?? "",
      exists:       String(entry.exists),
      laresRelPath: entry.laresRelPath ?? "",
      contentHash:  entry.contentHash,
    },
  };
}

// wikitext-filter → TW5 canonical (mirrors Node tw-filter.ts logic)
function toCanonicalWikitext(expr: string): string {
  return expr
    .replace(/\ball\[memes\]/g, "all[tiddlers]")
    .replace(/\btoml:([\w-]+)\[/g, "field:$1[");
}

// ---------------------------------------------------------------------------
// Public API (mirrors tw-filter.ts)
// ---------------------------------------------------------------------------

/**
 * Filter ClosureEntry objects using the wikitext-filter dialect (browser-side).
 * Async — uniform contract with the Node filterMemesWikitext() path.
 */
export async function filterMemesWikitext(
  allEntries: readonly ClosureEntry[],
  expr: string,
): Promise<ClosureEntry[]> {
  const wiki = getWiki(allEntries);
  const titles = wiki.filterTiddlers(toCanonicalWikitext(expr));
  const byUri = new Map(allEntries.map((e) => [e.uri, e]));
  return titles.map((t) => byUri.get(t)).filter((e): e is ClosureEntry => e !== undefined);
}

/** Backward-compat alias — prefer filterMemesWikitext for new code. */
export const filterMemesTW = filterMemesWikitext;

/** Legacy name — backward compat. */
export const filterMemesBrowser = filterMemesWikitext;

/**
 * Pre-compute multiple named filter results (browser sync version).
 */
export async function precomputeRooms(
  allEntries: readonly ClosureEntry[],
  rooms: Record<string, string>,
): Promise<Record<string, string[]>> {
  const wiki = getWiki(allEntries);
  const result: Record<string, string[]> = {};
  const byUri = new Map(allEntries.map((e) => [e.uri, e]));
  for (const [roomId, expr] of Object.entries(rooms)) {
    const titles = wiki.filterTiddlers(toCanonicalWikitext(expr));
    result[roomId] = titles.filter((t) => byUri.has(t));
  }
  return result;
}
