import { describe, expect, test } from "vitest";
import * as ed from "@noble/ed25519";
import { signAntigenEntry, antigenEntryBytes, antigenActCid, foldAntigenVerdicts, foldAntigenSet, makeMultiSigQuorumVerifier, denyingQuorumVerifier, type KapaeAntigenEntry, type KahuQuorumSeats } from "../src/kapae-antigen.js";
import { antigenEntriesFromBoard } from "../src/antigen-board.js";
import { mutableLarRecord } from "../src/base-doc.js";
import { hex } from "../src/crypto.js";
const EPOCH="charter-a", victim="deadbeef".repeat(8), seeds=[new Uint8Array(32).fill(1),new Uint8Array(32).fill(2),new Uint8Array(32).fill(3)];
const sign=(s:Uint8Array)=>(b:Uint8Array)=>ed.signAsync(b,s).then(hex), pub=(s:Uint8Array)=>ed.getPublicKeyAsync(s).then(hex), verifier=makeMultiSigQuorumVerifier();
async function roster():Promise<KahuQuorumSeats>{return {keys:await Promise.all(seeds.map(pub)),threshold:2,sealEpochCid:EPOCH};}
async function entry(action:"kapae"|"un_kapae",parents:string[]=[],pair=seeds.slice(0,2)):Promise<KapaeAntigenEntry>{return signAntigenEntry({nym:victim,action,parents,sealEpochCid:EPOCH},await Promise.all(pair.map(async s=>({signer:await pub(s),sign:sign(s)}))));}
describe("Kapae antigen causal frontier",()=>{
 test("valid descendant withdraws founded ban",async()=>{const a=await entry("kapae"),b=await entry("un_kapae",[a.actCid]),r=await roster();expect((await foldAntigenVerdicts([a,b],r,verifier)).get(victim)).toBe("withdrawn");expect((await foldAntigenSet([a,b],r,verifier)).has(victim)).toBe(false);});
 test("concurrent ban/lift is unsettled and fail-closed in either order",async()=>{const a=await entry("kapae",[],seeds.slice(0,2)),b=await entry("un_kapae",[],seeds.slice(1,3)),r=await roster();expect((await foldAntigenVerdicts([a,b],r,verifier)).get(victim)).toBe("unsettled");expect((await foldAntigenVerdicts([b,a],r,verifier)).get(victim)).toBe("unsettled");expect((await foldAntigenSet([a,b],r,verifier)).has(victim)).toBe(false);});
 test("missing parent is unavailable",async()=>{const a=await entry("kapae",["sha256:missing"]);expect((await foldAntigenVerdicts([a],await roster(),verifier)).get(victim)).toBe("unavailable");});
 test("parent order and duplicates do not change semantic bytes or CID",async()=>{const a=await entry("kapae",["p","q"]),b=await entry("kapae",["q","p","p"]);expect(Buffer.from(antigenEntryBytes(a)).toString("hex")).toBe(Buffer.from(antigenEntryBytes(b)).toString("hex"));expect(a.actCid).toBe(b.actCid);expect(a.actCid).toBe(antigenActCid({kind:a.kind,nym:a.nym,action:a.action,parents:a.parents,sealEpochCid:a.sealEpochCid}));});
 test("semantic tamper is rejected by quorum verification",async()=>{const a=await entry("kapae"),b={...a,action:"un_kapae" as const};expect((await foldAntigenVerdicts([b],await roster(),verifier)).get(victim)).toBeUndefined();expect((await foldAntigenSet([b],await roster(),verifier)).has(victim)).toBe(false);});
 test("a signed act whose semantic CID alone mutates is rejected before frontier folding",async()=>{const a=await entry("kapae"),b={...a,actCid:`sha256:${"0".repeat(64)}`};expect((await foldAntigenVerdicts([b],await roster(),verifier)).get(victim)).toBe("rejected");expect((await foldAntigenSet([b],await roster(),verifier)).has(victim)).toBe(false);});
 test("wrong charter quorum is ignored",async()=>{const a=await signAntigenEntry({nym:victim,action:"kapae",parents:[],sealEpochCid:"charter-b"},await Promise.all(seeds.slice(0,2).map(async s=>({signer:await pub(s),sign:sign(s)}))));expect((await foldAntigenSet([a],await roster(),verifier)).has(victim)).toBe(false);});
 test("threshold, duplicate signer, and deny-default controls remain fail-closed",async()=>{const a=await entry("kapae",[],[seeds[0]!]);const dup={...a,signatures:[a.signatures[0]!,a.signatures[0]!]};expect((await foldAntigenSet([a],await roster(),verifier)).has(victim)).toBe(false);expect((await foldAntigenSet([dup],await roster(),verifier)).has(victim)).toBe(false);expect((await foldAntigenSet([a],await roster(),denyingQuorumVerifier)).has(victim)).toBe(false);});
 test("foreign domain and malformed/torn board records never enter the fold",async()=>{const a=await entry("kapae"),foreign={...a,kind:"foreign/domain" as typeof a.kind}, tiddlers:Record<string, unknown>={};tiddlers.good=mutableLarRecord("good",{text:JSON.stringify(a)},"test");tiddlers.foreign=mutableLarRecord("foreign",{text:JSON.stringify(foreign)},"test");tiddlers.torn=mutableLarRecord("torn",{text:"not-json"},"test");expect(antigenEntriesFromBoard({schemaVersion:"0.1",tiddlers} as never)).toHaveLength(1);expect((await foldAntigenSet([foreign],await roster(),verifier)).has(victim)).toBe(false);});
 test("an empty roster and a non-roster signer cannot authorize a ban",async()=>{const outsider=new Uint8Array(32).fill(9), a=await signAntigenEntry({nym:victim,action:"kapae",parents:[],sealEpochCid:EPOCH},await Promise.all([seeds[0]!,outsider].map(async s=>({signer:await pub(s),sign:sign(s)}))));expect((await foldAntigenSet([a],await roster(),verifier)).has(victim)).toBe(false);expect((await foldAntigenSet([a],{keys:[],threshold:2,sealEpochCid:EPOCH},verifier)).has(victim)).toBe(false);});
});
