#!/usr/bin/env python3
"""Audit crosswalk source completeness against staging files.

For every spell row in the crosswalk, checks each PLAIN_LANE staging file that
is NOT listed in the row's Source Book(s) column. If the spell name (or any
alias) appears as a line-opening token in that staging file, the spell is
reported as a candidate for a missing lane.

Usage:
    python3 scripts/audit_crosswalk_source_completeness.py
    python3 scripts/audit_crosswalk_source_completeness.py --write
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

# Pull in sibling script so we can reuse shared logic.
sys.path.insert(0, str(Path(__file__).parent))
import build_becmi_spell_staging_multi as multi  # noqa: E402

ROOT = Path("/home/joshu/Synthetic-Dream-Machine")
DEFAULT_CHAPTER = ROOT / "Flying_Triremes_and_Laser_Swords/Flying_Triremes_and_Laser_Swords_06_Powers_and_ECM.md"
DEFAULT_CROSSWALK = ROOT / "_todo/TODO_BECMI_Spell_Effect_Crosswalk.md"
DEFAULT_OUTPUT = ROOT / "_todo/TODO_Audit_Crosswalk_Source_Completeness.md"

# Lines in staging files that begin with these prefixes are section markers,
# not spell-title lines. We skip them to avoid false-positive matches.
_SKIP_PREFIX_RE = re.compile(
    r"^(?:\[|#|```|>|\||\s*\d+\.\s|\*{1,3}$|---)"
)

# A "sourcing note" line in Master staging that starts with the spell name is
# a cross-reference pointer, not a real description. We want to surface it as a
# candidate (so the reviewer can decide), but flag it differently.
_SOURCING_NOTE_RE = re.compile(r"\[.*?sourcing note", re.I)


def is_description_opener(line: str) -> bool:
    """Return True if `line` looks like the opening of a spell description block."""
    stripped = line.strip()
    if not stripped:
        return False
    # Must start with uppercase or digit (spell titles).
    if not (stripped[0].isupper() or stripped[0].isdigit()):
        return False
    # Skip lines that are clearly structural: annotations, headings, fences, etc.
    if _SKIP_PREFIX_RE.match(stripped):
        return False
    return True


def find_next_meaningful_line(lines: list[str], start: int) -> str:
    """Return the first non-empty line at or after `start`, or ''."""
    for line in lines[start:]:
        stripped = line.strip()
        if stripped:
            return stripped
    return ""


def line_has_sourcing_note(line: str) -> bool:
    return bool(_SOURCING_NOTE_RE.search(line))


def audit_lane(
    spell_row: multi.SpellRow,
    lane: str,
    lane_lines: list[str],
) -> list[dict]:
    """Return a list of hit-dicts for any occurrences of `spell_row` in `lane_lines`."""
    aliases = multi.spell_aliases(spell_row.classic_name, spell_row.card_heading)
    alias_norms = {multi.norm(alias) for alias in aliases}

    hits: list[dict] = []
    seen_linenos: set[int] = set()

    for lineno, raw_line in enumerate(lane_lines, start=1):
        stripped = raw_line.strip()
        if not is_description_opener(stripped):
            continue
        candidate_norm = multi.norm(stripped.rstrip("*"))
        if candidate_norm not in alias_norms:
            continue
        if lineno in seen_linenos:
            continue
        seen_linenos.add(lineno)

        # Peek at the next few lines to give a useful preview
        next_line = find_next_meaningful_line(lane_lines, lineno)  # lineno is 1-based; lines[lineno] is next
        is_cross_ref = line_has_sourcing_note(next_line) or line_has_sourcing_note(stripped)

        # Classify the hit for the reviewer
        if is_cross_ref:
            disposition = "cross-ref-only (sourcing note)"
        elif next_line.startswith("Range:"):
            disposition = "likely description (Range: follows)"
        elif any(next_line.startswith(k) for k in ("Duration:", "Effect:", "Permanent")):
            disposition = "likely description (stat header follows)"
        else:
            disposition = "review needed"

        hits.append(
            {
                "spell": spell_row.classic_name,
                "lane": lane,
                "lineno": lineno,
                "preview": stripped[:80],
                "next_line": next_line[:60],
                "disposition": disposition,
            }
        )

    return hits


def build_report(all_hits: list[dict]) -> str:
    lines = [
        "# Audit: Crosswalk Source Completeness",
        "",
        "Generated by `scripts/audit_crosswalk_source_completeness.py`.",
        "",
        "Each row below represents a spell found in a staging file lane that is **not** "
        "listed in the crosswalk's Source Book(s) column. Review each hit and classify "
        "as `fix`, `false-positive`, or `cross-ref-only`.",
        "",
        "| Spell | Missing Lane | Line # | Preview | Next Line | Disposition |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for h in all_hits:
        preview = h["preview"].replace("|", "\\|")
        next_line = h["next_line"].replace("|", "\\|")
        lines.append(
            f"| {h['spell']} | {h['lane']} | {h['lineno']} "
            f"| `{preview}` | `{next_line}` | {h['disposition']} |"
        )
    lines += ["", f"**Total candidates: {len(all_hits)}**", ""]
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--chapter", type=Path, default=DEFAULT_CHAPTER,
    )
    parser.add_argument(
        "--crosswalk", type=Path, default=DEFAULT_CROSSWALK,
    )
    parser.add_argument(
        "--output", type=Path, default=DEFAULT_OUTPUT,
    )
    parser.add_argument(
        "--write", action="store_true",
        help="Write the report to --output in addition to printing to stdout.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    crosswalk_text = args.crosswalk.read_text(encoding="utf-8")
    chapter_text = args.chapter.read_text(encoding="utf-8")

    rows = multi.parse_spell_rows(crosswalk_text, chapter_text)

    # Load each staging file's lines once.
    lane_lines: dict[str, list[str]] = {
        lane: path.read_text(encoding="utf-8").splitlines()
        for lane, path in multi.PLAIN_LANE_PATHS.items()
    }

    all_hits: list[dict] = []

    for row in rows:
        present_lanes = set(row.source_lanes)
        for lane, lines in lane_lines.items():
            if lane in present_lanes:
                continue  # already in crosswalk
            hits = audit_lane(row, lane, lines)
            all_hits.extend(hits)

    # Sort: lane first, then spell name
    all_hits.sort(key=lambda h: (h["lane"], h["spell"]))

    report = build_report(all_hits)
    print(report)

    if args.write:
        args.output.write_text(report, encoding="utf-8")
        print(f"\nReport written to: {args.output}")


if __name__ == "__main__":
    main()
