/**
 * The genesis bake must REFUSE when the plugin build attestation it folds into the actor seed is
 * absent, never mint a seed that silently excludes it. `deriveGenesisActorSeed`'s own law reads an
 * absent attestation path as "folds nothing" — correct for the pure fold (a seed derivation that must
 * never throw on a partial tree) — but the BAKE sits a layer above: it is the one act that is supposed
 * to see the whole plugin build, and today it proceeded anyway, producing a DIFFERENT, unattested seed
 * under the same "the bake succeeded" exit code. That is the episkopos's L3 finding.
 *
 * The attestation file is a gitignored BUILD ARTIFACT (`dist-plugin/`, regenerated by
 * `pnpm --filter @lararium/tw5 build:plugin`), never a tracked source file — moving it aside for the
 * red case and restoring it in `finally` touches no git-tracked byte and leaves no watcher behind.
 */
import { afterEach, describe, expect, test } from "vitest";
import { spawnSync } from "node:child_process";
import { existsSync, mkdtempSync, readFileSync, renameSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = fileURLToPath(new URL(".", import.meta.url));
const SCRIPT = join(HERE, "..", "scripts", "build-genesis-island.ts");
const ATTESTATION = join(HERE, "..", "..", "lararium-tw5", "dist-plugin", "lares-memetic-wikitext.attestation.json");
const BACKUP = `${ATTESTATION}.genesis-attestation-required-test-backup`;

const made: string[] = [];
afterEach(() => {
  for (const d of made.splice(0)) rmSync(d, { recursive: true, force: true });
  if (existsSync(BACKUP) && !existsSync(ATTESTATION)) renameSync(BACKUP, ATTESTATION);
});

function bake(genesisDir: string) {
  return spawnSync(process.execPath, ["--import", "tsx", SCRIPT, "--genesis", genesisDir], {
    cwd: join(HERE, ".."),
    encoding: "utf8",
    timeout: 60_000,
  });
}

describe("★ the genesis bake refuses an absent attestation, never bakes an unattested seed ★", () => {
  test("RED: an absent attestation refuses — no seed.json, a non-zero exit, a named cure", () => {
    expect(existsSync(ATTESTATION)).toBe(true); // the control precondition: the repo carries one today
    const genesisDir = mkdtempSync(join(tmpdir(), "genesis-bake-absent-"));
    made.push(genesisDir);
    renameSync(ATTESTATION, BACKUP);
    try {
      const r = bake(genesisDir);
      expect(r.status).not.toBe(0);
      expect(r.stderr + r.stdout).toMatch(/attestation missing/);
      expect(r.stderr + r.stdout).toMatch(/build:plugin/);
      expect(existsSync(join(genesisDir, "seed.json"))).toBe(false);
    } finally {
      renameSync(BACKUP, ATTESTATION);
    }
  });

  test("CONTROL: the attestation present bakes a seed that folds it", () => {
    const genesisDir = mkdtempSync(join(tmpdir(), "genesis-bake-present-"));
    made.push(genesisDir);
    const r = bake(genesisDir);
    expect(r.status).toBe(0);
    const seedPath = join(genesisDir, "seed.json");
    expect(existsSync(seedPath)).toBe(true);
    expect(JSON.parse(readFileSync(seedPath, "utf8"))).toHaveProperty("tiddlers");
  });
});
