/**
 * Parity tests — verify TypeScript runtime matches golden fixtures from Python.
 * Fixtures generated by: python /tmp/gen_fixtures.py
 */

import { describe, test, expect } from "@jest/globals";
import { readFileSync } from "fs";
import { join, resolve, dirname } from "path";
import { fileURLToPath } from "url";

import { resolveLarUri } from "@lararium/core";
import { readCarrier, createLarariumRuntime } from "../src/node-host.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const FIXTURES_PATH = resolve(__dirname, "../../..", "lares/lararium-node/fixtures.golden.json");
const fixtures = JSON.parse(readFileSync(FIXTURES_PATH, "utf8")) as {
  resolver: Record<string, {
    uri: string; root: string; child_path: string[]; path: null;
    resource_path: string; kind: string; exists: boolean; virtual: boolean;
  }>;
  carrier: Record<string, {
    uri: string; path: null;
    metadata: Record<string, unknown>;
    implements: string[];
    shape: { valid: boolean; rating: string; depth_state: string; diagnostics: unknown[] };
  }>;
  compiler: {
    minimal_boot_count: number;
    minimal_boot_uris: string[];
    full_boot_count: number;
    receipt_sha256: string;
    receipt_meme_count: number;
  };
  indexes: {
    carrier_count: number;
    carrier_uris: string[];
    interface_count: number;
    invariant_count: number;
  };
};

const runtime = createLarariumRuntime({ writeback: false });

// ---------------------------------------------------------------------------
// Resolver parity
// ---------------------------------------------------------------------------

describe("resolver parity", () => {
  for (const [uri, expected] of Object.entries(fixtures.resolver)) {
    test(`resolve ${uri}`, () => {
      const actual = resolveLarUri(uri);
      expect(actual.uri).toBe(expected.uri);
      expect(actual.root).toBe(expected.root);
      expect([...actual.childPath]).toEqual(expected.child_path);
      expect(actual.kind).toBe(expected.kind);
      expect(actual.virtual).toBe(expected.virtual);
    });
  }
});

// ---------------------------------------------------------------------------
// Carrier parity
// ---------------------------------------------------------------------------

describe("carrier parity", () => {
  for (const [uri, expected] of Object.entries(fixtures.carrier)) {
    test(`carrier ${uri}`, () => {
      const actual = readCarrier(uri);
      expect(actual.uri).toBe(expected.uri);
      expect(actual.shape.valid).toBe(expected.shape.valid);
      expect(actual.shape.rating).toBe(expected.shape.rating);
      expect([...actual.implements].sort()).toEqual([...expected.implements].sort());
    });
  }
});

// ---------------------------------------------------------------------------
// Compiler parity
// ---------------------------------------------------------------------------

describe("compiler parity", () => {
  test("minimal boot meme count matches Python", () => {
    const artifact = runtime.compileMinimalBoot();
    expect(artifact.memeCount).toBe(fixtures.compiler.minimal_boot_count);
  });

  test("minimal boot URIs match Python (order-insensitive)", () => {
    const artifact = runtime.compileMinimalBoot();
    const actual = artifact.closure.map((e) => e.uri).sort();
    const expected = [...fixtures.compiler.minimal_boot_uris].sort();
    expect(actual).toEqual(expected);
  });

  test("minimal boot URI list starts at AGENTS entry point", () => {
    const artifact = runtime.compileMinimalBoot();
    const uris = artifact.closure.map((e) => e.uri);
    expect(uris[0]).toBe("lar:///AGENTS");
  });

  test("full boot meme count matches Python", () => {
    const artifact = runtime.compileFullBoot();
    expect(artifact.memeCount).toBe(fixtures.compiler.full_boot_count);
  });

  test("boot receipt meme count matches Python", async () => {
    const artifact = runtime.compileMinimalBoot();
    const receipt = await runtime.compileBootReceipt(artifact);
    expect(receipt.memeCount).toBe(fixtures.compiler.receipt_meme_count);
  });
});

// ---------------------------------------------------------------------------
// Index parity
// ---------------------------------------------------------------------------

describe("index parity", () => {
  test("carrier index count matches Python", () => {
    const carriers = runtime.compileCarrierIndex();
    expect(carriers.length).toBe(fixtures.indexes.carrier_count);
  });

  test("carrier index URIs match Python (order-insensitive)", () => {
    const carriers = runtime.compileCarrierIndex();
    const actual = carriers.map((c) => c.uri).sort();
    const expected = [...fixtures.indexes.carrier_uris].sort();
    expect(actual).toEqual(expected);
  });
});

// ---------------------------------------------------------------------------
// Hostful URI tests
// ---------------------------------------------------------------------------

import { parseHostfulLarUri, isHostfulLarUri } from "@lararium/core";

describe("hostful URI", () => {
  test("isHostfulLarUri detects hostful form", () => {
    expect(isHostfulLarUri("lar://claude:session@elyncia.app/ha.ka.ba/api/v0.1/mu")).toBe(true);
    expect(isHostfulLarUri("lar:///AGENTS")).toBe(false);
    expect(isHostfulLarUri("lar:///ha.ka.ba/api/v0.1/mu")).toBe(false);
  });

  test("parseHostfulLarUri extracts authority components", () => {
    const r = parseHostfulLarUri("lar://claude:session@elyncia.app/ha.ka.ba/api/v0.1/mu");
    expect(r.authority.alias).toBe("claude");
    expect(r.authority.tier).toBe("session");
    expect(r.authority.host).toBe("elyncia.app");
    expect(r.root).toBe("ha.ka.ba");
    expect(r.virtual).toBe(true);
    expect(r.laresRelPath).toBeNull();
  });

  test("parseHostfulLarUri handles alias without tier", () => {
    const r = parseHostfulLarUri("lar://joshu@elyncia.app/LARES");
    expect(r.authority.alias).toBe("joshu");
    expect(r.authority.tier).toBe("");
    expect(r.authority.host).toBe("elyncia.app");
    expect(r.root).toBe("LARES");
  });

  test("resolveLarUri rejects hostful URI with clear error", () => {
    expect(() => resolveLarUri("lar://claude:session@elyncia.app/ha.ka.ba/api/v0.1/mu"))
      .toThrow(/hostless/);
  });

  test("hostful resolution is always virtual — never resolves to lares file", () => {
    const r = parseHostfulLarUri("lar://operator:trajectory@dreamnet.local/ha.ka.ba/api/v0.1/lararium");
    expect(r.laresRelPath).toBeNull();
    expect(r.kind).toBe("caps-virtual");
  });
});
